name: Pipeline Completo - Prova DevOps



on:

  workflow_dispatch:

  push:

    branches: [ main ]



permissions:

  contentes: write  # üî• d√° permiss√£o pro GitHub Actions publicar no gh-pages



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar c√≥digo

        uses: actions/checkout@v4



      - name: Criar arquivo ZIP

        run: zip -r release.zip .



      - name: Publicar artefato ZIP

        uses: actions/upload-artifact@v4

        with:

          name: release-package

          path: release.zip



  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Baixar c√≥digo

        uses: actions/checkout@v4



      - name: Deploy no GitHub Pages

        uses: peaceiris/actions-gh-pages@v3

        with:

          GitHub_token: ${{ secrets.GITHUB_TOKEN }}

          publish branch: gh-pages

          publish_dir: ./
